"""day 6 email notification tracking

Revision ID: 5821be4db3a8
Revises: 0003
Create Date: 2026-08-22 15:16:25.882510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5821be4db3a8'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_chat_message_session_id', table_name='chat_message')
    op.alter_column('chat_session', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_session', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('email_notification', sa.Column('provider_message_id', sa.String(length=255), nullable=True))
    op.add_column('email_notification', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.alter_column('email_notification', 'recipient',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'info@moinsystemsai.com'::character varying"))
    op.alter_column('email_notification', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('email_notification', 'attempted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_email_notification_lead_id', table_name='email_notification')
    op.alter_column('knowledge_chunk', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('knowledge_chunk', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_knowledge_chunk_document_id', table_name='knowledge_chunk')
    op.drop_index('ix_knowledge_chunk_embedding', table_name='knowledge_chunk', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('knowledge_document', 'data_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'cleaned_validated'::character varying"))
    op.alter_column('knowledge_document', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_knowledge_document_category', table_name='knowledge_document')
    op.alter_column('lead_submission', 'lead_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'New'::character varying"))
    op.alter_column('lead_submission', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead_submission', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lead_submission', 'lead_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'New'::character varying"))
    op.create_index('ix_knowledge_document_category', 'knowledge_document', ['category'], unique=False)
    op.alter_column('knowledge_document', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_document', 'data_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'cleaned_validated'::character varying"))
    op.create_index('ix_knowledge_chunk_embedding', 'knowledge_chunk', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('ix_knowledge_chunk_document_id', 'knowledge_chunk', ['document_id'], unique=False)
    op.alter_column('knowledge_chunk', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_chunk', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('ix_email_notification_lead_id', 'email_notification', ['lead_id'], unique=False)
    op.alter_column('email_notification', 'attempted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_notification', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('email_notification', 'recipient',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'info@moinsystemsai.com'::character varying"))
    op.drop_column('email_notification', 'retry_count')
    op.drop_column('email_notification', 'provider_message_id')
    op.alter_column('chat_session', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_session', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_chat_message_session_id', 'chat_message', ['session_id'], unique=False)
    op.alter_column('chat_message', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
